"""SpatioLD: spatial local diversity analysis for spatial omics."""

from .core import SpatioLD
from .diversity import (
    DEFAULT_RADII,
    compute_local_diversity,
    compute_local_diversity_multi_radius,
    compute_neighborhood_diversity,
)
from .modeling import (
    fit_lasso_for_celltype,
    fit_lasso_for_radius,
    fit_ols_for_celltype,
    fit_ols_for_radius,
    prepare_radius_design,
    top_abs_terms,
)
from .permutation import (
    compute_nd_permutation_distribution,
    compute_nd_permutation_mean,
    compute_nd_permutation_pvals,
)
from .pipeline import (
    align_expression_and_metadata,
    build_significance_mask,
    cluster_local_diversity_profiles,
    compute_global_shannon_entropy,
    compute_hvg_scanpy,
    compute_sample_vs_null_summary,
    compute_svg_morans_i,
    fit_all_genes,
    fit_single_gene_radius_model,
    make_spline_basis,
    prepare_shared_components,
    preprocess_expression_matrix,
    reconstruct_radius_effect,
    summarize_local_diversity_by_cell_type,
)
from .plotting import (
    plot_gene_effect_volcano,
    plot_gene_set_venn,
    plot_kmeans_spatial_maps,
    plot_mean_diversity_by_cell_type,
    plot_sample_vs_null_curve,
    plot_significant_diversity_maps,
    plot_spatial_cell_types,
)

__all__ = [
    "DEFAULT_RADII",
    "SpatioLD",
    "compute_local_diversity",
    "compute_local_diversity_multi_radius",
    "compute_neighborhood_diversity",
    "compute_nd_permutation_pvals",
    "compute_nd_permutation_mean",
    "compute_nd_permutation_distribution",
    "compute_global_shannon_entropy",
    "preprocess_expression_matrix",
    "align_expression_and_metadata",
    "summarize_local_diversity_by_cell_type",
    "compute_sample_vs_null_summary",
    "cluster_local_diversity_profiles",
    "build_significance_mask",
    "make_spline_basis",
    "prepare_shared_components",
    "fit_single_gene_radius_model",
    "reconstruct_radius_effect",
    "fit_all_genes",
    "compute_svg_morans_i",
    "compute_hvg_scanpy",
    "plot_spatial_cell_types",
    "plot_mean_diversity_by_cell_type",
    "plot_sample_vs_null_curve",
    "plot_kmeans_spatial_maps",
    "plot_significant_diversity_maps",
    "plot_gene_effect_volcano",
    "plot_gene_set_venn",
    "prepare_radius_design",
    "fit_lasso_for_celltype",
    "fit_ols_for_celltype",
    "fit_lasso_for_radius",
    "fit_ols_for_radius",
    "top_abs_terms",
]
